#!/usr/bin/env ruby

=begin
 Copyright (c) 2010 David Andersen | davidx.org | davidx at davidx.org

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
=end

require 'rubygems'
require 'choice'

$:.unshift File.dirname(__FILE__) + '/../../lib/'

require 'ganglia'

output = `df -lk|grep -v "Mounted on"`
lines = output.split(/\n/)
data = {}
lines.each do |line|
  mounted, percentage, available, used, total, part = line.strip.split(/\s+/).reverse
  next unless total
  next if part == 'none'
  mounted_name = mounted.gsub(/\//, '_')

  data[mounted_name] = {
          :part => part,
          :total => total,
          :used => used,
          :available => available,
          :value => percentage.gsub(/%/, '').to_i,
          :mounted => mounted,
  }
end

data.each { |k, v|
  Ganglia.gmetric(
          :name =>"df" + k,
          :value => v[:value],
          :units => 'percentage',
          :type => 'uint32'
  )
}
