#!/usr/bin/env ruby

=begin
 Copyright (c) 2010 David Andersen | davidx.org | davidx at davidx.org

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
=end

require 'net/http'
require 'uri'

$: << File.dirname(__FILE__)
$: << File.dirname(__FILE__) + '/../../lib'
require 'ganglia'
require 'rubygems'
require 'choice'
require 'active_support'
include ActiveSupport::Inflector
     
Choice.options do
  header ''
  header 'Specific options:'

  option :url, :required => true do
    short '-u'
    long '--url=URL'
    desc 'The url you would like to graph(required)'
  end
  option :metric_name, :required => true do
    short '-n'
    long '--name=NAME'
    desc 'The name of the url metric(required)'
  end
  separator ''
  separator 'Common options: '

  option :help do
    long '--help'
    desc 'Show this message'
  end
end

def timed_request(options={}, &block)
  start = Time.now
  result = yield
  duration = Time.now - start
end

def get(url)
  Net::HTTP.get URI.parse(url)
end

url_response_time_value = timed_request do
  response = get Choice.choices[:url]
  p response if ENV.key?('GMETRICS_DEBUG')
end


choices=Choice.choices
url = Choice.choices[:url]
url_response_time_metric_name = choices[:metric_name] || "url_response_time_#{underscore(url)}"

Ganglia.gmetric(
    :name => url_response_time_metric_name,
    :value => url_response_time_value ,
    :units => "seconds",
    :type => 'float'
  )
